# Generated by Django 5.1.2 on 2024-10-17 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_recommender', '0002_language_delete_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Language',
            new_name='movie_name_list',
        ),
        migrations.RenameField(
            model_name='movie_name_list',
            old_name='name',
            new_name='movie_names',
        ),
    ]
