# Generated by Django 5.1.2 on 2024-10-17 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_recommender', '0004_rename_movie_names_movie_name_list_movies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='movie_name_list',
            new_name='Language',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='movies',
            new_name='name',
        ),
    ]
