# Generated by Django 5.1.2 on 2024-10-17 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_recommender', '0005_rename_movie_name_list_language_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Language',
            new_name='movie_name_list',
        ),
        migrations.RenameField(
            model_name='movie_name_list',
            old_name='name',
            new_name='movies',
        ),
    ]
