# Generated by Django 5.1.2 on 2024-10-17 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_recommender', '0007_rename_movies_movie_name_list_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='movie_name_list',
            new_name='Language',
        ),
    ]
