# Generated by Django 5.1.2 on 2024-10-18 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_recommender', '0008_rename_movie_name_list_language'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Language',
            new_name='movie_list_table',
        ),
        migrations.RenameField(
            model_name='movie_list_table',
            old_name='name',
            new_name='movie_list',
        ),
    ]
