# Generated by Django 5.1.2 on 2024-10-18 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_recommender', '0009_rename_language_movie_list_table_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='movie_list_table',
            new_name='Language',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='movie_list',
            new_name='name',
        ),
    ]
