# Generated by Django 5.1.2 on 2024-10-18 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_recommender', '0010_rename_movie_list_table_language_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Language',
            new_name='movie_list',
        ),
    ]
