# Generated by Django 5.1.2 on 2024-10-23 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_recommender', '0013_searchhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchHistory',
        ),
    ]
